name: Test and attest

on:
  workflow_call:
    inputs:
      arch:
        type: string
        description: Architecture used for the test
        required: true
        default: "am64" # amd64 or arm64
      attest:
        type: boolean
        description: Whether to attest the build provenance
        required: false
        default: false

permissions:
  contents: read
  id-token: write
  attestations: write

jobs:
  build:
    runs-on: ${{ inputs.arch == 'arm64' && 'ubuntu-22.04-arm' || 'ubuntu-latest' }}

    steps:
      - uses: actions/checkout@v4

      - name: Test artifacts
        run: |
          ${{ github.workspace }}/bombom-linux-${{ inputs.arch }}.bin -F json -f

      - name: Attest build provenance
        uses: actions/attest-build-provenance@00014ed6ed5efc5b1ab7f7f34a39eb55d41aa4f8 # v3.1.0
        id: attest-provenance
        if: ${{ inputs.attest }}
        with:
          subject-path: ${{ github.workspace }}/bombom-linux-${{ inputs.arch }}.bin

      - name: Export provenance bundle
        if: ${{ inputs.attest }}
        env:
          ATT_BUNDLE: ${{ steps.attest-provenance.outputs.bundle-path }}
        run: |
          set -euo pipefail
          cp "${{ env.ATT_BUNDLE }}" "${{ github.workspace }}/bombom-linux-${{ inputs.arch }}.bin.sigstore"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: bombom-linux-${{ inputs.arch }}
          path: |
            ${{ github.workspace }}/bombom-linux-${{ inputs.arch }}.bin
            ${{ github.workspace }}/bombom-linux-${{ inputs.arch }}.bin.sha256
            ${{ github.workspace }}/bombom-linux-${{ inputs.arch }}.bin.sigstore
